### ISSUE TITLE
DDD-Design: Company specific properties and forms

### ISSUE THREAD

**Issue by prolic** [proophsoftware/es-emergency-call#2]
Let's say you have a company with 20 fields, but some of those ask you to add more fields or remove some of them, because they don't have meaning to them. Also some fields are dependend only, so if field A exists, then show field B, otherwise hide field B. Or if field A exists, then field B can be of value "foo" and "bar", otherwise field B can be of value "bam" and "baz".

For the read model the queries might look something like this:

```
// try to find company specific form
$forms = $db->execute('SELECT * FROM CompanyDetailsForm WHERE company_id = 123');

if (! $forms) {
    // nothing found, use default company forms
    $form = $db->execute('SELECT * FROM CompanyDetailsForm WHERE company_id IS NULL');
}
```

So a first implementation of such a company aggregate can look like this:

```
class Company extends AggregateRoot
{
    private $properties;
    
    private $propertiesValidator;
    
    public static function with($id, array $properties, array $propertiesValidator)
    {
        InputFilter::factory($propertiesValidator)->isValid($properties);
        
        $self = new self();
        $self->recordThat(CompanyWasCreated::with($id, $properties, $propertiesValidator));
        
        return $self;
    }
    
    public function property($name)
    {
        return $this->properties[$name] ?? null;
    }
}
```

The code is not expected to work, just to demonstrate what it could look like. Are there any problems with this approach, are there better alternatives?

More questions would be:
- Is it possible to add custom events for a company that is somewhat db-configured and not hardcoded?
- Is it possible to add custom commands for a company, that is somewhat db-configured and not hardcoded?

**Comment by codeliner** [comment]
yes, such a design is possible with event sourcing. We've built part of a system in such a way.

Before I go into detail what we did and what are the lessons learned I'd like to stress the point that not every problem needs to be solved with event sourcing. If you use DDD techniques to identify different bounded contexts and you use modular or even microservices approach to structure your application/system then it is totally fine to use event sourcing in a behavior driven context and a more traditional approach in a data driven context.

Configuring properties of an entity is state driven. You offer the user a way to change shape of the state. The first question here is what is the context? When and why can user of the system add or remove properties of a company entity (I call it entity for now and not aggregate, because we're talking about a single object with an identity and state)? And how does such a change effect the rest of the system?

**Comment by prolic** [comment]
Not sure whether the user itself should be able to modify the properties / forms, this is something also a programmer could do (let's not overcomplicate the example).
A history is still interessting, let's take an example, company creates a request for XY.
Because when form A (f.e. create a request XY) was filled with template A, and template A was then updated to A', then when I load form A again, I need the template A and not template A'. But when I create a new request, then form A needs template A' of course.
This is still possible with a data driven system that is not event sourced, but as you know, I can answer really strange questions some product manager comes up with, when I have a complete history of everything that ever happened.

**Comment by codeliner** [comment]
I see you want the history ;). Was the same reason for us to use event sourcing in that context, too. I try to explain what we've built, but I can't show example code. You'll end up with a very generic, even CRUD-ish solution but you can still use some event sourcing goodness ....

You have to treat the aggregate as a data container in this case. The aggregate has a single `data` property (more props are possible if needed of course) and this data is described by a schema.

We use [JsonSchema](http://json-schema.org/) for that purpose. In it's simplest form the aggregate provides create, update and deactivate methods. Those methods are very generic, especially the update method. Our update method takes [json-patch](http://jsonpatch.com/) commands and applies them to `data`, but not without recording a `DataPatched` event before. This means that each json patch is put in an event, which gets recorded and then the patch gets applied.

The interesting thing here is, that the aggregate does not know how `data` is structured. This is described by the schema. Now you can decide if the schema should be hardcoded or maybe allowed to change. In our case we even have a microservice where users can modify the schema (change the shape of the data). But the schema is versioned so only new aggregates use the new schema and old aggregates use older versions of the schema. There are business rules defined when an existing aggregate can also use a newer schema. Here real event sourcing comes into play and helps us to control the process, coordinate the services (schema mgmt microservice, core application, follow up systems)

The `DataPatched` event is interesting. First it only gets recorded if validation of `data` against `schema` is ok. We perform a dry run, record the event, apply the patch

```php
class DataContaienr extends AbstractJsonPatchAggregate
{
  public function update(JsonPatch $patch, SchemaValidator $schemaValidator): void
  {
    //data is an array and we create a copy to perform dry run on it
    $data = $this->data;
    $modifiedData = $this->applyPatch($data, $patch);
    if(!$schemaValidator->isValid($this->jsonSchema, $data)) {
      throw PatchFailed::for($this, $patch);
    }
    $this->recordThat(new DataPatched($patch));
  }

  private function onDataPatched(DataPatched $event)
  {
    $this->data = $this->applyPatch($this->data, $event->patch());
  }
}
```

Later we added use case specific methods which still modify data via patch internally but within a specific scenario. Then we have something like `ScenarioHappened extends DataPatched`.
`ScenarioHappened` even contains getter methods for value objects. It scans the recorded json patch internally and turns the value of one or more patch operations into a value object so you can use that in specific projections like you would do with a normal domain event. 

Performance goes done a bit of course but this is super flexible and still enables advanced usage of event sourcing. But it also has pitfalls. For example schema changes required by new features are not that easy. In most cases we were able to use system commands with prepared json patches and sent them to all effected aggregates. Not as easy as running a migration script during deployment but worked for us.

Bonus: You can combine such a backend with a frontend that can render forms dynamically based on a given json schema. Here is one promising project: https://github.com/mozilla-services/react-jsonschema-form

We've built our own JS frontend for that purpose but next time I'd use the linked package or similar (frontend was/is hard work).

**Comment by prolic** [comment]
Great, thanks.

**Comment by codeliner** [comment]
you're welcome
